/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:1c5e4e48-466a-4a65-aa92-5b575a567817",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_LaqezHwRl",
    "aws_user_pools_web_client_id": "48vncgi0f42b3t32ftr9rqv89f",
    "oauth": {}
};


export default awsmobile;
